lzc-sdk-version: "0.1"
name: LetterSpace
package: xyz.mxue.letterspace
version: 0.0.3
description: LetterSpace是一个开源的时事通讯应用程序,让您完全控制订阅者列表和电子邮件活动。
homepage: https://github.com/dcodesdev/LetterSpace
author: dcodesdev
application:
  subdomain: letterspace
  background_task: false
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://letterspace.xyz.mxue.letterspace.lzcapp:5000/
services:
  letterspace-db:
    image: registry.lazycat.cloud/mxuexxmy/library/postgres:843c69368d9b1504
    user: root
    environment:
      - POSTGRES_DB=letterspace
      - POSTGRES_USER=letterspaceuser
      - POSTGRES_PASSWORD=letterspacepass
    binds:
      - /lzcapp/var/data:/var/lib/postgresql/data
    health_check:
      test:
        - CMD-SHELL
        - pg_isready -q -d letterspace -U letterspaceuser
      start_period: 120s
  letterspace:
    image: registry.lazycat.cloud/mxuexxmy/dcodesdev/letterspace:5ae3ab1bf3c0a7b2
    user: root
    environment:
      - DATABASE_URL=postgresql://letterspaceuser:letterspacepass@letterspace-db.xyz.mxue.letterspace.lzcapp:5432/letterspace?schema=public
      - JWT_SECRET=bdgyUgEkSn8FjdEUT60puMpAgyiQEP3sM/jwPebALY0=
    depends_on:
      - letterspace-db
    health_check:
      test:
        - CMD-SHELL
        - timeout 10s bash -c ':> /dev/tcp/127.0.0.1/5000' || exit 1
      start_period: 45s
